CREATE TABLE public.settings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key text UNIQUE NOT NULL,
    value jsonb,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL
);

-- RLS Policies
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated user to read settings"
ON public.settings FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Allow admin to update settings"
ON public.settings FOR UPDATE
TO authenticated
USING ((SELECT role FROM public.users WHERE auth_id = auth.uid()) = 'admin');

-- Function to update the updated_at timestamp
CREATE OR REPLACE FUNCTION public.handle_settings_update()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to update the timestamp
CREATE TRIGGER on_settings_update
BEFORE UPDATE ON public.settings
FOR EACH ROW
EXECUTE FUNCTION public.handle_settings_update();

-- Insert default settings
INSERT INTO public.settings (key, value)
VALUES
    ('business_info', '{"name": "VerifyFlow Inc.", "email": "admin@verifyflow.com", "phone": "+1 (555) 123-4567", "address": "123 Business St, Toronto, ON M5V 2H1", "website": "https://verifyflow.com"}'),
    ('regional', '{"province": "Ontario", "supported_provinces": ["Ontario", "Quebec", "British Columbia", "Alberta", "Manitoba", "Saskatchewan", "Nova Scotia"] }'),
    ('system', '{"maintenance_mode": false, "debug_mode": false}'); 